import os
import time
import enchant

import re

d = enchant.Dict("en_US")
d.add("func")
d.add("struct")
d.add("rc")
d.add("src")
d.add("mv")
d.add("cr")
d.add("auth")
d.add("nil")
d.add("checkNil")
d.add("canChange")
d.add("mk")
d.add("ConflictingDatastoreFound")
d.add("ConnectedIso")
d.add("Kubernetes")
d.add("kubernetes")
d.add("Licensor")
d.add("licensable")
d.add('cAdvisor')
d.add("bool")
d.add("const")
d.add("unix")
d.add("MERCHANTABILITY")
d.add("Vastech")
d.add("Redistributions")
d.add("blockquote")
d.add("html")
d.add("srcs")
d.add("textarea")
d.add("tbody")
d.add("TODO")
d.add("kubelet")
d.add("tfoot")
d.add("CloudFlare")
d.add("SELinux")
d.add("Flocker")
d.add("ReadOnly")
d.add("repo")
d.add("iSCSI")
d.add("stdin")
d.add("finalizer")
d.add("finalizers")
d.add("kubectl")
d.add("yaml")
d.add("ThirdPartyResource")
d.add("kube")
d.add("http")
d.add("cgroups")
d.add("atEOF")
d.add("UUID")
d.add("ACName")
d.add("ACKind")
d.add("passwd")
d.add("args")
d.add("chan")
d.add("ReadFile")
d.add("committer")
d.add("redis")
d.add("guestbook")
d.add("backend")
d.add("filename")
d.add("golang")
d.add("sysctl")
d.add("kubenet")
d.add("portManager")
d.add("nsenter")
d.add("config")
d.add("podIP")
d.add("cniPlugin")
d.add("hostport")
d.add("vendorDir")
d.add("shaper")
d.add("boolean")
d.add("protobuf")
d.add("proto")
d.add("lookup")
d.add("langAliasType")
d.add("Matcher")
d.add("subtag")
d.add("langNoIndexOffset")
d.add("IsPrivateUse")
d.add("regionID")
d.add("ValueError")
d.add("stringSet")
d.add("isList")
d.add("haveRegion")
d.add("GOPATH")
d.add("endif")
d.add("xargs")
d.add("SecurityContext")
d.add("metadata")
d.add("ConfigMap")
d.add("hostname")
d.add("apiserver")
d.add("nginx")
d.add("github")
d.add("linkPath")
d.add("fieldNum")
d.add("mline")
d.add("genericGenerator")
d.add("OpenAPI")
d.add("DeepCopy")
d.add("outType")
d.add("viMajor")
d.add("Clientset")
d.add("BackupStreamReader")
d.add("Isolator")
d.add("username")
d.add("NodePort")
d.add("maxID")
d.add("configMaps")
d.add("respErr")
d.add("okPod")
d.add("Timestamp")
d.add("oldPvc")
d.add("Marshaler")
d.add("poolID")
d.add("ddysher")
d.add("zmerlynn")
d.add("parseErr")
d.add("byteCount")
d.add("connectRequest")
d.add("testKubeletHostname")
d.add("localhostCert")
d.add("sortBy")
d.add("ImageStatusRequest")
d.add("patchEvent")
d.add("RemoveTags")
d.add("FindChildRequestType")
d.add("BackendHealth")
d.add("typeOf")
d.add("KeyPairs")
d.add("ContainerType")
d.add("defaultContainerName")
d.add("RunCommand")
d.add("cgroupName")
d.add("byHash")
d.add("DeleteSnapshotInput")
d.add("namespaceInfo")
d.add("inputValue")
d.add("restStorageBuilder")
d.add("codegen")
d.add("IsDomainName")
d.add("btrfs")
d.add("CurrentMetrics")
d.add("OpenSSH")
d.add("VolumeList")
d.add("volumeSize")
d.add("volumemanager")
d.add("tokenURL")
d.add("ipnet")
d.add("NewEtcd")
d.add("getStatus")
d.add("windowsConsole")
d.add("GetJob")
d.add("mapKey")
d.add("randomColor")
d.add("DNSIP")
d.add("waitStreamReply")
d.add("LabelSelector")
d.add("gceImage")
d.add("resourcequota")
d.add("oldPath")
d.add("netStat")
d.add("Glusterfs")
d.add("CompareTo")
d.add("maxCount")
d.add("prometheus")
d.add("IsNil")
d.add("tokenize")
d.add("wordpress")
d.add("ErrorCode")
d.add("certPath")
d.add("ctime")
d.add("cmdArgs")
d.add("newVol")
d.add("pName")
d.add("nginxImage")
d.add("timeutil")
d.add("cgroupRoot")
d.add("newEvent")
d.add("ClusterIP")
d.add("createIngress")
d.add("getDNSIP")
d.add("gbkcode")
d.add("NetworkList")
d.add("ipAddr")
d.add("EtcdError")
d.add("HTTPHeader")
d.add("OutOfDisk")
d.add("emptydir")
d.add("nfsMounter")
d.add("portName")
d.add("jUnit")
d.add("ByRule")
d.add("encoderFunc")
d.add("afterEach")
d.add("gotNodes")
d.add("Cephfs")
d.add("containerList")
d.add("curPods")
d.add("HostnameCheck")
d.add("closec")
d.add("jQuery")
d.add("newname")
d.add("failover")
d.add("newFile")
d.add("rrset")
d.add("GOROOT")
d.add("homedir")
d.add("Mesos")
d.add("NodeID")
d.add("TimedOut")
d.add("RedHat")
d.add("mysql")
d.add("maxPort")
d.add("restapi")
d.add("selinux")
d.add("rmdir")
d.add("AddWatch")
d.add("strconv")
d.add("unittest")
d.add("GetIP")
d.add("cinderVolume")
d.add("pageSize")
d.add("NotEqual")
d.add("RunTest")
d.add("iscsiadm")
d.add("logName")
d.add("datetime")
d.add("google")
d.add("clientset")
d.add("HostName")
d.add("printf")
d.add("devicemapper")
d.add("diskName")
d.add("cpulimit")
d.add("centos")
d.add("iface")
d.add("petset")
d.add("linux")





ok = set()
def eachFile(filepath):
    for root, dirs, files in os.walk(filepath):
#        print root
        for file in files:
            for line in open(os.path.join(root, file)):
                for i in line.split(" "):
                    if re.match('^[a-zA-Z]{5,20}$', i):
                        if d.check(i.strip("\r\n")):
                            continue
                        else:
                            ok.add(i)




eachFile("/home/tim/eclipse/workspace/src/k8s.io/kubernetes")


for i in ok:
    print i

print "disonnected" in ok